swj/urls.py
from django.urls import path
from . import views

app_name = 'swj'

urlpatterns = [
    # members views
    path('', views.main_page, name='main_page'),
    path('<int:id>/', views.member_detail, name='member_detail'),
    path('', views.homepage, name='homepage'),
    path('contributors', views.contributors, name='contributors'),
    path('members', views.members, name='members'),
    path('references', views.references, name='references'),
]

swjsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swj.urls', namespace='swj')),
]

swj/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Member.Status.PUBLISHED)

class Member(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    name = models.CharField(max_length=1000)
    slug = models.SlugField(max_length=10, unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='swj_members')
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.name

swj/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

swj/views.py
from django.shortcuts import render, get_object_or_404
from .models import Member
from django.contrib.postgres.search import SearchVector
from django.contrib.postgres.search import TrigramSimilarity
from .forms import SearchForm

def main_page(request):
    return render(request,
                 'swj/pages/mainpage.html',
                )


def member_detail(request, id):
    member = get_object_or_404(Member,
                             id=id,
                             status=Member.Status.PUBLISHED)
    return render(request,
                  'swj/member/detail.html',
                  {'member': member})

def homepage(request):
    return render(request,
                  'swj/pages/list.html')

def contributors(request):
    return render(request, 
                  'swj/pages/contributors.html')


def members(request):
    form = SearchForm()
    query = None
    results = []
    members = Member.published.all()

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Member.published.annotate(similarity=TrigramSimilarity('name', query),
            ).filter(similarity__gt=0.1).order_by('-similarity') 

    return render(request, 
                  'swj/pages/members.html',
                  {'members': members,
                   'form': form,
                   'query': query,
                   'results': results})

def references(request):
    return render(request, 
                  'swj/pages/references.html')

swj/templates/swj/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Society of Women Journalists</title>
  <link href="{% static "css/base1.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <!-- Start of nav bar -->
  <div id="header">
    <a href="{% url "swj:homepage" %}">
      <span class="logo">SWJ1894</span>
    </a>
      <ul class="menu">
        <li>
          <a href="{% url "swj:references" %}">
            References</a>
        </li>
        <li>
          <a href="{% url "swj:contributors" %}">
            Contributors
          </a>
        </li>
        <li>
          <a href="{% url "swj:members" %}">
            SWJ Members <i class="fa fa-search"></i></a>
        </li>
      </ul>
  </div>
  <!-- End of Nav bar -->

  <!-- Start of content bar -->
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <!-- end of Content bar -->
</body>
</html>

swj/templates/swj/member/detail.html
{% extends "swj/base.html" %}

{% block title %}{{ member.name }}{% endblock %}

{% block content %}
  <h1>{{ member.name }}</h1>
  <p class="date">
    Published {{ member.publish }} by {{ member.author }}
  </p>
  {{ member.body|linebreaks }}
{% endblock %}

swj/templates/swj/pages/contributors.html
{% extends "swj/base.html" %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Start of content bar -->
  <div id="content">
    {% block content %}
    <h1>Contributors page </h1>
    <h2>In this page we can show the contributors</h2>
    {% endblock %}
  </div>
  <!-- end of Content bar -->
</body>
</html>

swj/templates/swj/pages/mainpage.html
{% extends "swj/base.html" %}

{% block title %}SWJ{% endblock %}

{% block content %}
  <h1>Society of Women Journalists Homepage</h1>
  <h2>In this page we can show the about section and other functions as shown in the homepage</h2>
{% endblock %}

swj/templates/swj/pages/members.html
{% extends "swj/base.html" %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Start of content bar -->
  <div id="content">
    {% block content %}

  <!-- Start of the Search Engine bar-->
    {% if query %}
    <h1>Name containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for member in results %}
    <h2>
      <a href="{% url 'swj:member_detail' member.id %}">
        {{ member.name }}
      </a>
    </h2>
    {% empty %}
    <p>There are no results for your query.</p>
    {% endfor %}
    <p>
    <button type="submit" id="againButton" 

    style="
    cursor: pointer;
    height: 32px;
    width: 40px;
    display: inline-block;
    font-weight: 400;
    text-align: center;
    background-color: #efe3e3;
    padding: 6px 12px;
    font-size: 1rem;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    border-color: #5cbdb9;"
    >

      <a href="{% url "swj:members" %}"><i class="fa fa-undo"></i></a></p>
    </button>
    {% else %}
    
    <!-- Search bar form -->
    <!-- Form style changes the fit -->
    <!-- Input style changes the search bar look -->
    <form method="get" id="search" 

    style="
    width: 100%;
    position: relative;
    display: flex;"
    >

      <input type="text" name="query" placeholder="Search..." id="search-input"

    style="
    width: 100%;
    position: relative;
    display: flex;
    border: 3px solid #00B4CC;
    border-right: none;
    padding: 5px;
    height: 40px;
    font-size: 30px;
    border-radius: 5px 0 0 5px;
    outline: none;
    color: #00B4CC;"
    >

      <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
      </button>
    </form>
    {% endif %}
    <!-- End of Search Engine bar-->

  <h1>Members page </h1>
  
  <!-- Start of Post-->
  {% for member in members %}
    <h2>
      <a href="{% url 'swj:member_detail' member.id %}">
        {{ member.name }}
      </a>
    </h2>
    <p class="date">
      Published {{ member.publish }} by {{ member.author }}
    </p>
    {{ member.body|truncatewords:30|linebreaks }}
  {% endfor %}
    {% endblock %}
  </div>
  <!-- end of Content bar -->
</body>
</html>

swj/templates/swj/pages/references.html
{% extends "swj/base.html" %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- Start of content bar -->
  <div id="content">
    {% block content %}
    <h1>References page </h1>
    <h2>In this page we can show the references</h2>
    {% endblock %}
  </div>
  <!-- end of Content bar -->
</body>
</html>